<a href="https://colab.research.google.com/github/emiraksakal/dersnotlar-nb/blob/main/KwithOld.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.cluster import KMeans

In [63]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [64]:
df = pd.read_csv('/content/drive/MyDrive/collab/NTP2.csv',low_memory=False)

In [65]:
df1 = pd.read_csv('/content/drive/MyDrive/collab/Tuesday-WorkingHours.pcap_ISCX.csv',low_memory=False)

In [66]:
df2 = pd.read_csv('/content/drive/MyDrive/collab/LDAP3.csv',low_memory=False)

In [67]:
df1.columns =df1.columns.str.upper()

In [68]:
df.columns =df.columns.str.upper()

In [69]:
df2.columns =df.columns.str.upper()

In [ ]:
df.columns

In [ ]:
df1.columns

In [ ]:
print(df.columns.intersection(df1.columns))

In [73]:
x = pd.concat([df1,df], join="inner", sort=False)

In [74]:
x

,DESTINATION PORT,FLOW DURATION,TOTAL FWD PACKETS,TOTAL BACKWARD PACKETS,TOTAL LENGTH OF FWD PACKETS,TOTAL LENGTH OF BWD PACKETS,FWD PACKET LENGTH MAX,FWD PACKET LENGTH MIN,FWD PACKET LENGTH MEAN,FWD PACKET LENGTH STD,...,MIN_SEG_SIZE_FORWARD,ACTIVE MEAN,ACTIVE STD,ACTIVE MAX,ACTIVE MIN,IDLE MEAN,IDLE STD,IDLE MAX,IDLE MIN,LABEL
0,88,640,7,4,440.0,358.0,220.0,0.0,62.857143,107.349008,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
1,88,900,9,4,600.0,2944.0,300.0,0.0,66.666667,132.287566,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
2,88,1205,7,4,2776.0,2830.0,1388.0,0.0,396.571429,677.274651,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
3,88,511,7,4,452.0,370.0,226.0,0.0,64.571429,110.276708,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
4,88,773,9,4,612.0,2944.0,306.0,0.0,68.000000,134.933317,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217003,63125,37146,200,0,88000.0,0.0,440.0,440.0,440.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP
217004,12431,42011,200,0,88000.0,0.0,440.0,440.0,440.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP
217005,881,40375,200,0,88000.0,0.0,440.0,440.0,440.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP
217006,7051,59116,200,0,88000.0,0.0,440.0,440.0,440.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP
217007,60495,34660,103,0,45320.0,0.0,440.0,440.0,440.000000,0.000000,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP

In [75]:
x = pd.concat([df2,x], join="inner", sort=False)

In [76]:
z = x

In [77]:
classes =x[' LABEL']   
print(classes.value_counts())

BENIGN         433018
DrDoS_NTP      216194
DrDoS_LDAP     181413
FTP-Patator      7938
SSH-Patator      5897
Name:  LABEL, dtype: int64

In [78]:
x.loc[x[" LABEL"] == "BENIGN", " LABEL"] = 0 ## 5e eşitle?
x.loc[x[" LABEL"] == "FTP-Patator", " LABEL"] = 1
x.loc[x[" LABEL"] == "SSH-Patator", " LABEL"] = 3
x.loc[x[" LABEL"] == "DrDoS_NTP", " LABEL"] = 2
x.loc[x[" LABEL"] == "DrDoS_LDAP", " LABEL"] = 4

In [79]:
df1.dropna()
futurex=x.iloc[:,0:-1]
futurex.replace([np.inf, -np.inf], np.nan, inplace=True)
for i in futurex.columns:
    if(i==' Label'):
        futurex[i]=futurex[i].fillna('BENIGN')
    else:
        futurex[i]=futurex[i].fillna(futurex[i].median())

In [80]:
y = x

In [81]:
y

,DESTINATION PORT,FLOW DURATION,TOTAL FWD PACKETS,TOTAL BACKWARD PACKETS,TOTAL LENGTH OF FWD PACKETS,TOTAL LENGTH OF BWD PACKETS,FWD PACKET LENGTH MAX,FWD PACKET LENGTH MIN,FWD PACKET LENGTH MEAN,FWD PACKET LENGTH STD,...,MIN_SEG_SIZE_FORWARD,ACTIVE MEAN,ACTIVE STD,ACTIVE MAX,ACTIVE MIN,IDLE MEAN,IDLE STD,IDLE MAX,IDLE MIN,LABEL
0,19271,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
1,39709,2,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
2,51217,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
3,36924,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
4,54420,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217003,63125,37146,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
217004,12431,42011,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
217005,881,40375,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
217006,7051,59116,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2
217007,60495,34660,103,0,45320.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2

In [82]:
x.drop([' LABEL'], axis=1)

,DESTINATION PORT,FLOW DURATION,TOTAL FWD PACKETS,TOTAL BACKWARD PACKETS,TOTAL LENGTH OF FWD PACKETS,TOTAL LENGTH OF BWD PACKETS,FWD PACKET LENGTH MAX,FWD PACKET LENGTH MIN,FWD PACKET LENGTH MEAN,FWD PACKET LENGTH STD,...,ACT_DATA_PKT_FWD,MIN_SEG_SIZE_FORWARD,ACTIVE MEAN,ACTIVE STD,ACTIVE MAX,ACTIVE MIN,IDLE MEAN,IDLE STD,IDLE MAX,IDLE MIN
0,19271,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,39709,2,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,51217,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,36924,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,54420,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,1,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217003,63125,37146,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,199,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217004,12431,42011,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,199,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217005,881,40375,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,199,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217006,7051,59116,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,199,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
217007,60495,34660,103,0,45320.0,0.0,440.0,440.0,440.0,0.0,...,102,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [83]:
x = futurex.copy()
kmeans =KMeans(5)
kmeans.fit(x)

KMeans(n_clusters=5)

In [84]:
clusters = x.copy()
clusters[' LABEL'] = kmeans.fit_predict(x)

from sklearn import preprocessing
x_scaled = preprocessing.scale(x)
x_scaled

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_data.py:236: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  "Numerical issues were encountered "

array([[-0.03685887, -0.25746493, -0.03276537, ..., -0.0549359 ,
        -0.18862529, -0.18170051],
       [ 0.86666758, -0.25746488, -0.03276537, ..., -0.0549359 ,
        -0.18862529, -0.18170051],
       [ 1.37541513, -0.25746493, -0.03276537, ..., -0.0549359 ,
        -0.18862529, -0.18170051],
       ...,
       [-0.849847  , -0.25564233,  0.26500111, ..., -0.0549359 ,
        -0.18862529, -0.18170051],
       [-0.57708263, -0.2547963 ,  0.26500111, ..., -0.0549359 ,
        -0.18862529, -0.18170051],
       [ 1.78557848, -0.25590032,  0.11912562, ..., -0.0549359 ,
        -0.18862529, -0.18170051]])

In [85]:
kmeans_new = KMeans(5)
kmeans.fit(x_scaled)
cluster_new = x.copy()
cluster_new [' LABEL'] = kmeans_new.fit_predict(x_scaled)
cluster_new

,DESTINATION PORT,FLOW DURATION,TOTAL FWD PACKETS,TOTAL BACKWARD PACKETS,TOTAL LENGTH OF FWD PACKETS,TOTAL LENGTH OF BWD PACKETS,FWD PACKET LENGTH MAX,FWD PACKET LENGTH MIN,FWD PACKET LENGTH MEAN,FWD PACKET LENGTH STD,...,MIN_SEG_SIZE_FORWARD,ACTIVE MEAN,ACTIVE STD,ACTIVE MAX,ACTIVE MIN,IDLE MEAN,IDLE STD,IDLE MAX,IDLE MIN,LABEL
0,19271,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
1,39709,2,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
2,51217,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,36924,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,54420,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217003,63125,37146,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
217004,12431,42011,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
217005,881,40375,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
217006,7051,59116,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
217007,60495,34660,103,0,45320.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1

In [108]:
cluster_new['matchx'] = np.where(cluster_new[' LABEL'] == z[' LABEL'], 'True', 'False')

In [109]:
cluster_new

,DESTINATION PORT,FLOW DURATION,TOTAL FWD PACKETS,TOTAL BACKWARD PACKETS,TOTAL LENGTH OF FWD PACKETS,TOTAL LENGTH OF BWD PACKETS,FWD PACKET LENGTH MAX,FWD PACKET LENGTH MIN,FWD PACKET LENGTH MEAN,FWD PACKET LENGTH STD,...,ACTIVE STD,ACTIVE MAX,ACTIVE MIN,IDLE MEAN,IDLE STD,IDLE MAX,IDLE MIN,LABEL,match,matchx
0,19271,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP,False,False
1,39709,2,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP,False,False
2,51217,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP,False,False
3,36924,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP,False,False
4,54420,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217003,63125,37146,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,False,False
217004,12431,42011,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,False,False
217005,881,40375,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,False,False
217006,7051,59116,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,False,False
217007,60495,34660,103,0,45320.0,0.0,440.0,440.0,440.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,BENIGN,False,False

In [111]:
z

,DESTINATION PORT,FLOW DURATION,TOTAL FWD PACKETS,TOTAL BACKWARD PACKETS,TOTAL LENGTH OF FWD PACKETS,TOTAL LENGTH OF BWD PACKETS,FWD PACKET LENGTH MAX,FWD PACKET LENGTH MIN,FWD PACKET LENGTH MEAN,FWD PACKET LENGTH STD,...,MIN_SEG_SIZE_FORWARD,ACTIVE MEAN,ACTIVE STD,ACTIVE MAX,ACTIVE MIN,IDLE MEAN,IDLE STD,IDLE MAX,IDLE MIN,LABEL
0,19271,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_LDAP
1,39709,2,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_LDAP
2,51217,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_LDAP
3,36924,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_LDAP
4,54420,1,2,0,2944.0,0.0,1472.0,1472.0,1472.0,0.0,...,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_LDAP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217003,63125,37146,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP
217004,12431,42011,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP
217005,881,40375,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP
217006,7051,59116,200,0,88000.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP
217007,60495,34660,103,0,45320.0,0.0,440.0,440.0,440.0,0.0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,DrDoS_NTP

In [107]:
classes11 =cluster_new[' LABEL']   
print(classes11.value_counts())

BENIGN         572668
DrDoS_NTP      181548
DrDoS_LDAP      74674
FTP-Patator     15556
SSH-Patator        14
Name:  LABEL, dtype: int64

In [105]:
cluster_new[' LABEL'] = cluster_new[' LABEL'].apply(str)

In [106]:
cluster_new.loc[cluster_new[" LABEL"] == "1", " LABEL"] = "BENIGN"
cluster_new.loc[cluster_new[" LABEL"] == "0", " LABEL"] = "DrDoS_NTP"
cluster_new.loc[cluster_new[" LABEL"] == "4", " LABEL"] = "DrDoS_LDAP"
cluster_new.loc[cluster_new[" LABEL"] == "2", " LABEL"] = "FTP-Patator"
cluster_new.loc[cluster_new[" LABEL"] == "3", " LABEL"] = "SSH-Patator"

In [102]:
classes111 =y[' LABEL']   

print(classes111.value_counts())

BENIGN         433018
DrDoS_NTP      216194
DrDoS_LDAP     181413
FTP-Patator      7938
SSH-Patator      5897
Name:  LABEL, dtype: int64

In [90]:
y[' LABEL'] = y[' LABEL'].apply(str)

In [98]:
# y.loc[y[" LABEL"] == "0", " LABEL"] = "BENIGN"
# y.loc[y[" LABEL"] == "2", " LABEL"] = "DrDoS_NTP"
# y.loc[y[" LABEL"] == "4", " LABEL"] = "DrDoS_LDAP"
# y.loc[y[" LABEL"] == "1", " LABEL"] = "FTP-Patator"
# y.loc[y[" LABEL"] == "deneme", " LABEL"] = "SSH-Patator"

In [99]:
classes1112 =y[' LABEL']   

print(classes1112.value_counts())

BENIGN         433018
DrDoS_NTP      216194
DrDoS_LDAP     181413
FTP-Patator      7938
SSH-Patator      5897
Name:  LABEL, dtype: int64

In [110]:
classes11111 =cluster_new['matchx']   
print(classes11111.value_counts())

## 65.17 percent

False    501758
True     342702
Name: matchx, dtype: int64